# Generated by Django 6.0.2 on 2026-02-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(choices=[('friday', 'Friday'), ('public_holiday', 'Public Holiday'), ('religion_day', 'Religion Day'), ('company_off', 'Company Off')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='holidays_date_c1d23c_idx'), models.Index(fields=['holiday_type'], name='holidays_holiday_19b24a_idx')],
            },
        ),
    ]
