# Generated by Django 6.0.2 on 2026-02-24 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('CL', 'Casual Leave'), ('PL', 'Privilege Leave'), ('ML', 'Maternity Leave'), ('LWP', 'Leave Without Pay'), ('WL', 'Wedding Leave')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'db_table': 'leaves',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='leaves_employe_0be14d_idx'), models.Index(fields=['date'], name='leaves_date_e56689_idx'), models.Index(fields=['leave_type'], name='leaves_leave_t_64c248_idx'), models.Index(fields=['status'], name='leaves_status_1a86dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date', 'leave_type'), name='unique_leave')],
            },
        ),
    ]
