# Generated by Django 6.0.2 on 2026-02-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_repeated',
            field=models.BooleanField(default=False, help_text='Mark as duplicate/repeated record'),
        ),
    ]
